import pandas as pd
import matplotlib.pyplot as plt

# Load the data generated by your compiled C binary
df = pd.read_csv("audio/dashboard_data.csv")

fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 10), sharex=True, sharey=True)

# Panel 1: Pure Source Track Reference from C
ax1.plot(df["Time_ms"], df["Reference"], label="Unfiltered Input", color="blue", linewidth=1.5)
ax1.set_title("1. REFERENCE: C Generated High-Frequency Sweep Reference")
ax1.grid(True, linestyle=":", alpha=0.6)
ax1.legend(loc="upper right")

# Panel 2: Class BD Output from C
ax2.plot(df["Time_ms"], df["Class_BD"], label="Class BD", color="green", linewidth=1.5)
ax2.set_title("2. OUTPUT: Class BD Stage (Transparent 4th-Order)")
ax2.grid(True, linestyle=":", alpha=0.6)
ax2.legend(loc="upper right")

# Panel 3: Class AD Output from C
ax3.plot(df["Time_ms"], df["Class_AD"], label="Class AD", color="darkcyan", linewidth=1.5)
ax3.set_title("3. OUTPUT: Class AD Stage (Aggressive 8th-Order Attenuation)")
ax3.set_xlabel("Window Timeline Segment (Milliseconds)")
ax3.grid(True, linestyle=":", alpha=0.6)
ax3.legend(loc="upper right")

plt.tight_layout()
plt.show()
